export type { NotesSchema, Note } from './model/types/NotesSchema'
export { notesReducer, notesActions } from './model/slice/notesSlice'
export { getFilteredNotes } from './model/selectors/getFilteredNotes'
export { getNearbyNoteId } from './model/selectors/getNearbyNoteId'
export { NoteField } from './ui/NoteFiled/NoteField'
export { NoteList } from './ui/NoteList'
